# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvprobit <- function(y, x, m, n, t, ncores) {
    .Call(`_rankchoiceR_mvprobit`, y, x, m, n, t, ncores)
}

rankchoice <- function(y, x, m, n, t, ncores, scale) {
    .Call(`_rankchoiceR_rankchoice`, y, x, m, n, t, ncores, scale)
}

ranktop <- function(y, x, m, n, t, ncores, scale) {
    .Call(`_rankchoiceR_ranktop`, y, x, m, n, t, ncores, scale)
}

